version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/notifier"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/detector"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/deterrent"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/backup"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/config-api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/log-streamer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/trainer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/training-controller"
    schedule:
      interval: "weekly"
