#!/bin/bash
set -e
uv run --no-project --with ruff==0.15.7 bash scripts/lint.sh
PYTHONPATH=services/web/src:shared uv run --no-project --with-requirements services/web/requirements.txt --with pytest --with httpx --with pillow --with mypy --with types-PyYAML --with types-requests --with types-redis python -m pytest -q services/web/tests/test_fdy_0570_regression.py
PYTHONPATH=services/web/src:shared uv run --no-project --with-requirements services/web/requirements.txt --with pytest --with httpx --with pillow --with mypy --with types-PyYAML --with types-requests --with types-redis python -m pytest -q services/web/tests
MYPYPATH=services/web/src:shared uv run --no-project --with-requirements services/web/requirements.txt --with pytest --with httpx --with pillow --with mypy --with types-PyYAML --with types-requests --with types-redis python -m mypy services/web/src shared --ignore-missing-imports --explicit-package-bases
PYTHONPATH=services/detector/src:shared uv run --no-project --with PyYAML --with redis --with numpy --with opencv-python-headless --with pydantic --with cryptography --with requests --with pytest --with httpx --with pillow --with mypy --with types-PyYAML --with types-requests --with types-redis python -m pytest -q services/detector/tests
PYTHONPATH=services/trainer/src:shared uv run --no-project --with PyYAML --with redis --with numpy --with opencv-python-headless --with pydantic --with cryptography --with requests --with pytest --with httpx --with pillow --with mypy --with types-PyYAML --with types-requests --with types-redis python -m pytest -q services/trainer/tests
PYTHONPATH=services/notifier/src:shared uv run --no-project --with-requirements services/notifier/requirements.txt --with pytest --with httpx --with pillow --with mypy --with types-PyYAML --with types-requests --with types-redis python -m pytest -q services/notifier/tests
MYPYPATH=services/notifier/src:shared uv run --no-project --with-requirements services/notifier/requirements.txt --with pytest --with httpx --with pillow --with mypy --with types-PyYAML --with types-requests --with types-redis python -m mypy services/notifier/src shared --ignore-missing-imports --explicit-package-bases
PYTHONPATH=services/deterrent/src:shared uv run --no-project --with-requirements services/deterrent/requirements.txt --with pytest --with httpx --with pillow --with mypy --with types-PyYAML --with types-requests --with types-redis python -m pytest -q services/deterrent/tests
MYPYPATH=services/deterrent/src:shared uv run --no-project --with-requirements services/deterrent/requirements.txt --with pytest --with httpx --with pillow --with mypy --with types-PyYAML --with types-requests --with types-redis python -m mypy services/deterrent/src shared --ignore-missing-imports --explicit-package-bases
PYTHONPATH=services/log-streamer/src:shared uv run --no-project --with-requirements services/log-streamer/requirements.txt --with pytest --with httpx --with pillow --with mypy --with types-PyYAML --with types-requests --with types-redis python -m pytest -q services/log-streamer/tests
echo "ALL TESTS PASSED!"
